name: .NET Avalonia CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Replace with your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # - name: Run tests
      #   run: dotnet test --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true --self-contained true -o ${{ github.workspace }}/publish --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KeepMeAlive-exe
          path: ${{ github.workspace }}/publish
